Update formatting
Signed-off-by: Joe Ma <rikkaneko23@gmail.com>

diff --git a/debian/files/dtb_cp b/debian/files/dtb_cp
--- a/debian/files/dtb_cp
+++ b/debian/files/dtb_cp
@@ -11,7 +11,7 @@ dtb_files='<DTB_FILES>'
 
 # passing the kernel version is required
 if [ -z "${version}" ]; then
-	echo >&2 "E: dtb_cp: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
+	echo -e >&2 "E: dtb_cp: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
 	exit 2
 fi
 
@@ -21,19 +21,19 @@ for dtb_file in ${dtb_files}; do
 	target="/boot/${dtb_file}-${version}"
 
 	if [ -e "${source1}" ]; then
-		echo -n "I: dtb_cp: symlinking ${source1} to ${target}"
+		echo -e -n "I: dtb_cp: symlinking ${source1} to ${target}"
 		ln -sf "$(basename "${source1}")" "${target}"
 	elif [ -f "${source2}" ]; then
-		echo "I: dtb_cp: copying ${source2} to ${target}"
+		echo -e "I: dtb_cp: copying ${source2} to ${target}"
 		install -m 644 "${source2}" "${target}"
 	else
 		# search other kernel packages for a dtb before failing
 		res="$(find /usr/lib/linux-image* -name ${dtb_file} | linux-version sort --reverse | head -n1)"
 		if [ -f "${res}" ]; then
-			echo "I: dtb_cp: copying ${res} to ${target}"
+			echo -e "I: dtb_cp: copying ${res} to ${target}"
 			install -m 644 "${res}" "${target}"
 		else
-			echo >&2 "E: dtb_cp: dtb file ${dtb_file} not found"
+			echo -e >&2 "E: dtb_cp: dtb file ${dtb_file} not found"
 			exit 3
 		fi
 	fi
